"""Thin stdio shim: a FastMCP server whose tools forward to the daemon.

The shim is a near-zero-logic process. It exposes a SEPARATE ``FastMCP``
instance whose tools are *forwarders* generated by reflecting the real tool
registry — each forwarder preserves the real tool's identity (signature,
docstring, name, annotations) so an MCP client sees a byte-identical schema.

On a tool call the forwarder:

* :func:`ensure_daemon` — discover a running daemon via the lockfile (probe it),
  otherwise spawn a fully detached daemon and poll until it is connectable.
* sends a ``request`` frame with a fresh ``request_id`` over a cached connection
  (one per shim process, identified by a per-process ``session_id``);
* reads the matching ``response`` (correlated by ``request_id``);
* on a mid-call connection drop, attempts EXACTLY ONE reconnect, then raises a
  clear, actionable error — never hangs (socket timeouts bound every wait).

A background heartbeat timer pings the daemon every ``heartbeat_interval``
seconds over the same connection, using the connection's send-lock so it never
corrupts an in-flight request frame.

CUTOVER IS OFF in this phase: ``app.main`` still runs the in-process server by
default. The shim is reached only when ``ORIGIN_PRO_MCP_USE_DAEMON`` is truthy.
"""
from __future__ import annotations

import functools
import inspect
import os
import subprocess
import sys
import tempfile
import threading
import time
import uuid
from typing import Optional, Tuple

from mcp.server.fastmcp import FastMCP

from . import transport
from .daemon import (
    DISPATCH_KILL_GRACE_DEFAULT,
    DISPATCH_TIMEOUT_DEFAULT,
    default_lockfile_path,
    iter_registered_tools,
    read_lockfile,
)
from .transport import FrameError

HOST = "127.0.0.1"


# --------------------------------------------------------------------------- #
# Daemon discovery + auto-spawn                                                #
# --------------------------------------------------------------------------- #


def _probe(host: str, port: int, token: str, timeout: float) -> bool:
    """Return True if a daemon is accepting connections at host/port/token."""
    try:
        conn = transport.connect(host, port, token)
    except OSError:
        return False
    try:
        conn.settimeout(timeout)
        conn.send_frame({"type": "heartbeat", "ts": time.time()})
        return True
    except (OSError, FrameError):
        return False
    finally:
        conn.close()


def _try_existing(lockfile_path: str,
                  connect_timeout: float) -> Optional[Tuple[str, int, str]]:
    """Read the lockfile and probe it; return conn info if a daemon answers."""
    try:
        data = read_lockfile(lockfile_path)
    except (OSError, ValueError):
        return None  # missing / partially-written / garbage lockfile
    port, token = data.get("port"), data.get("token")
    if not port or not token:
        return None
    if _probe(HOST, port, token, connect_timeout):
        return HOST, port, token
    return None


def _spawn_daemon(lockfile_path: str,
                  env_extra: Optional[dict] = None) -> None:
    """Spawn a fully detached daemon process (`python -m ...daemon`).

    New session/process group, stdio to devnull, ``close_fds``. The daemon's
    ``SingletonGuard`` resolves a spawn race (two shims) — the loser exits and
    both shims then connect to the winner via the same lockfile.
    """
    env = os.environ.copy()
    env["ORIGIN_PRO_MCP_LOCKFILE"] = lockfile_path
    # Ensure the spawned interpreter can import the package even when the parent
    # relies on an in-process sys.path entry (e.g. pytest's ``pythonpath``).
    pkg_parent = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    existing = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = (
        pkg_parent + (os.pathsep + existing) if existing else pkg_parent
    )
    if env_extra:
        env.update(env_extra)

    kwargs = dict(
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        close_fds=True,
        env=env,
        # NOT os.getcwd(): when the shim is launched from WSL the inherited
        # working directory is a UNC path (\\wsl.localhost\...), which Windows
        # cannot use as a process CWD — it fails the spawn and flashes a console
        # window. A local temp dir is always a valid Windows CWD.
        cwd=tempfile.gettempdir(),
    )
    if sys.platform == "win32":
        DETACHED_PROCESS = 0x00000008
        kwargs["creationflags"] = (
            subprocess.CREATE_NEW_PROCESS_GROUP | DETACHED_PROCESS
        )
    else:
        kwargs["start_new_session"] = True

    subprocess.Popen(
        [sys.executable, "-m", "origin_pro_mcp.daemon"], **kwargs
    )


def ensure_daemon(lockfile_path: Optional[str] = None, *,
                  spawn: bool = True,
                  connect_timeout: float = 2.0,
                  spawn_timeout: float = 20.0,
                  poll_interval: float = 0.05,
                  max_poll_interval: float = 0.5) -> Tuple[str, int, str]:
    """Return ``(host, port, token)`` for a running daemon, spawning if needed.

    Reads the lockfile and probes it; if a daemon answers, returns its info.
    Otherwise (when ``spawn`` is True) spawns a detached daemon and polls — with
    capped backoff, bounded by ``spawn_timeout`` — for the lockfile to appear
    and become connectable. Raises :class:`RuntimeError` on total failure.
    """
    if lockfile_path is None:
        lockfile_path = default_lockfile_path()

    # Global kill-switch: ORIGIN_PRO_MCP_NO_SPAWN lets an operator stop the
    # daemon from the process manager and keep it stopped — no tool call will
    # auto-respawn it (a clear error is returned instead).
    _ns = os.environ.get("ORIGIN_PRO_MCP_NO_SPAWN")
    if _ns is not None and _ns.strip().lower() in ("1", "on", "true", "yes"):
        spawn = False

    info = _try_existing(lockfile_path, connect_timeout)
    if info is not None:
        return info

    if not spawn:
        raise RuntimeError(
            "The Origin daemon is not running and auto-spawn is disabled "
            f"(lockfile: {lockfile_path}). Start it with "
            "'python -m origin_pro_mcp.daemon' and retry."
        )

    _spawn_daemon(lockfile_path)

    deadline = time.monotonic() + spawn_timeout
    interval = poll_interval
    while time.monotonic() < deadline:
        info = _try_existing(lockfile_path, connect_timeout)
        if info is not None:
            return info
        time.sleep(interval)
        interval = min(interval * 1.5, max_poll_interval)

    raise RuntimeError(
        f"Timed out after {spawn_timeout:.0f}s waiting for the Origin daemon "
        f"to come up (lockfile: {lockfile_path}). Verify that "
        "'python -m origin_pro_mcp.daemon' can start on this machine."
    )


def _env_float(name: str, default: float) -> Optional[float]:
    """Parse a seconds env var mirroring the daemon: unset/unparseable -> default,
    an explicit off value -> None (disabled)."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    if raw.strip().lower() in ("off", "false", "no", "0", ""):
        return None
    try:
        return float(raw)
    except (TypeError, ValueError):
        return default


def _reconcile_call_timeout(call_timeout: float) -> float:
    """Ensure the client socket outlives the daemon's per-dispatch deadline.

    The daemon's two-phase timeout warns the client at the SOFT budget
    (``ORIGIN_PRO_MCP_DISPATCH_TIMEOUT``) and, if Origin stays wedged, force-kills
    it after the kill grace (``ORIGIN_PRO_MCP_DISPATCH_KILL_GRACE``) and replies.
    The client must keep its socket recv open long enough to RECEIVE that reply
    rather than tripping its own socket timeout first (which would surface a raw
    timeout instead of the daemon's actionable message). We size the call timeout
    to soft + grace plus a margin for the kill + reply round-trip. A soft budget
    of ``off``/``0`` disables the timeout and leaves the caller's value unchanged.
    """
    soft = _env_float("ORIGIN_PRO_MCP_DISPATCH_TIMEOUT", DISPATCH_TIMEOUT_DEFAULT)
    if soft is None or soft <= 0:
        return call_timeout  # dispatch timeout disabled
    grace = _env_float("ORIGIN_PRO_MCP_DISPATCH_KILL_GRACE", DISPATCH_KILL_GRACE_DEFAULT)
    total = soft + (grace if grace and grace > 0 else 0.0)
    return max(call_timeout, total + 15.0)


# --------------------------------------------------------------------------- #
# Shim client: cached connection, reconnect, heartbeat                         #
# --------------------------------------------------------------------------- #


class ShimClient:
    """One persistent connection to the daemon for a single shim process.

    All forwarders share this client. A per-process ``session_id`` ties every
    request to the same daemon session. Concurrent forwarder calls serialize on
    a call-lock (so a single connection's request/response pairs never
    interleave), while the heartbeat timer writes the socket independently under
    the connection's own send-lock. Correlation IDs are a second safety net.
    """

    def __init__(self, lockfile_path: Optional[str] = None, *,
                 session_id: Optional[str] = None,
                 heartbeat_interval: float = 10.0,
                 # Must exceed the daemon's session start_timeout (~45s for a
                 # cold Origin launch) so the first tool call doesn't give up
                 # while Origin is still launching.
                 call_timeout: float = 60.0,
                 allow_spawn: bool = True,
                 ensure_kwargs: Optional[dict] = None):
        self._lockfile_path = lockfile_path
        self._session_id = session_id or uuid.uuid4().hex
        self._heartbeat_interval = heartbeat_interval
        self._call_timeout = _reconcile_call_timeout(call_timeout)
        self._allow_spawn = allow_spawn
        # Opt in to attaching this session to the user's already-open Origin
        # (Origin.ApplicationSI) instead of a fresh isolated instance.
        _at = os.environ.get("ORIGIN_PRO_MCP_ATTACH")
        self._attach = _at is not None and _at.strip().lower() in (
            "1", "on", "true", "yes")
        self._ensure_kwargs = dict(ensure_kwargs or {})
        self._conn = None
        self._conn_lock = threading.Lock()   # guards connection lifecycle
        self._call_lock = threading.Lock()   # serializes send+recv per call
        self._hb_thread: Optional[threading.Thread] = None
        self._hb_stop: Optional[threading.Event] = None

    @property
    def session_id(self) -> str:
        return self._session_id

    # -- connection lifecycle ------------------------------------------------ #

    def _ensure_conn(self):
        with self._conn_lock:
            if self._conn is not None:
                return self._conn
            host, port, token = ensure_daemon(
                self._lockfile_path, spawn=self._allow_spawn,
                **self._ensure_kwargs,
            )
            conn = transport.connect(host, port, token,
                                     session_id=self._session_id)
            conn.settimeout(self._call_timeout)
            self._conn = conn
            self._start_heartbeat(conn)
            return conn

    def _reset_conn(self):
        with self._conn_lock:
            self._stop_heartbeat()
            if self._conn is not None:
                self._conn.close()
                self._conn = None

    def close(self):
        self._reset_conn()

    # -- heartbeat ----------------------------------------------------------- #

    def _start_heartbeat(self, conn):
        if not self._heartbeat_interval or self._heartbeat_interval <= 0:
            return
        stop = threading.Event()

        def _loop():
            while not stop.wait(self._heartbeat_interval):
                try:
                    conn.send_frame({"type": "heartbeat", "ts": time.time()})
                except (OSError, FrameError):
                    return  # connection gone; let the next call reconnect

        thread = threading.Thread(target=_loop, name="shim-heartbeat",
                                  daemon=True)
        self._hb_stop = stop
        self._hb_thread = thread
        thread.start()

    def _stop_heartbeat(self):
        if self._hb_stop is not None:
            self._hb_stop.set()
        self._hb_stop = None
        self._hb_thread = None

    # -- the forward path ---------------------------------------------------- #

    def call(self, name: str, kwargs: dict):
        """Forward one tool call; reconnect exactly once on a dropped link."""
        last_exc = None
        for _attempt in range(2):
            conn = self._ensure_conn()
            try:
                return self._exchange(conn, name, kwargs)
            except (OSError, FrameError) as exc:
                last_exc = exc
                self._reset_conn()
        raise RuntimeError(
            f"Lost the connection to the Origin daemon while calling {name!r} "
            f"and one reconnect attempt also failed ({last_exc}). The daemon "
            "may have exited — retry the call to respawn it."
        )

    def _exchange(self, conn, name: str, kwargs: dict):
        request_id = uuid.uuid4().hex
        with self._call_lock:
            conn.send_frame({
                "type": "request",
                "request_id": request_id,
                "session_id": self._session_id,
                "name": name,
                "kwargs": kwargs or {},
                "attach": self._attach,
            })
            while True:
                frame = conn.recv_frame()
                if frame is None:
                    raise FrameError("daemon closed the connection mid-call")
                if frame.get("type") != "response":
                    continue  # skip stray non-response frames (defensive)
                if frame.get("request_id") != request_id:
                    continue  # not our response — keep reading
                break
        if frame.get("ok"):
            result = frame.get("result")
            # One-shot lifecycle notice the daemon may piggyback on the first
            # successful response of a session (restart/ghost/attach context).
            notice = frame.get("notice")
            if notice:
                base = result if result is not None else ""
                return f"{base}\n\n[origin-mcp] {notice}"
            return result
        raise RuntimeError(frame.get("error") or "unknown daemon error")


# --------------------------------------------------------------------------- #
# Forwarder generation + shim server                                          #
# --------------------------------------------------------------------------- #


def _real_registry() -> dict:
    """The real FastMCP tool registry — ``{name: fn}`` for all 37 tools.

    Routes through :func:`~.daemon.iter_registered_tools` so a FastMCP internals
    change fails LOUD (RuntimeError) here rather than silently building a shim
    that forwards zero tools.
    """
    from . import server  # noqa: F401 — importing registers every tool
    from .app import mcp as real_mcp

    return iter_registered_tools(real_mcp)


def _make_forwarder(tool_name: str, real_fn, client: ShimClient):
    """A forwarder that is schema-identical to ``real_fn`` but calls the daemon.

    ``functools.wraps`` copies ``__doc__``/``__name__``/``__annotations__``/etc;
    an explicit ``__signature__`` guarantees FastMCP generates a byte-identical
    JSON schema (so MCP clients can't tell the shim from the in-process server).
    """
    sig = inspect.signature(real_fn)

    @functools.wraps(real_fn)
    def forwarder(*args, **kwargs):
        bound = sig.bind(*args, **kwargs)
        return client.call(tool_name, dict(bound.arguments))

    forwarder.__signature__ = sig
    forwarder.__name__ = real_fn.__name__
    forwarder.__doc__ = real_fn.__doc__
    forwarder.__annotations__ = dict(getattr(real_fn, "__annotations__", {}))
    return forwarder


def build_shim_server(client: ShimClient, *, name: str = "origin-pro") -> FastMCP:
    """Build a fresh shim ``FastMCP`` whose tools forward through ``client``.

    The Origin tools become daemon-forwarders, but the skill tools
    (``list_skills`` / ``get_skill``) read bundled markdown only — no COM — so
    they are registered LOCALLY on the shim and never routed to the daemon.
    """
    from .skills import SERVER_INSTRUCTIONS, SKILL_TOOL_NAMES, register_skills

    shim = FastMCP(name, log_level="ERROR", instructions=SERVER_INSTRUCTIONS)
    for tool_name, real_fn in _real_registry().items():
        if tool_name in SKILL_TOOL_NAMES:
            continue  # served locally below — never forward to the daemon
        shim.add_tool(_make_forwarder(tool_name, real_fn, client),
                      name=tool_name)
    register_skills(shim)
    return shim


_default_client: Optional[ShimClient] = None
_default_client_lock = threading.Lock()


def _get_default_client() -> ShimClient:
    global _default_client
    with _default_client_lock:
        if _default_client is None:
            _default_client = ShimClient()
        return _default_client


def run_stdio() -> None:
    """Run the shim's FastMCP stdio loop (the daemon-backed entrypoint).

    The heartbeat thread is a daemon thread, so process exit on stdin EOF is
    clean without an explicit join.
    """
    build_shim_server(_get_default_client()).run(transport="stdio")
